plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/swhitelex/weeecycle"
publishOrigin = "config"

[build.environment]
npm_config_ignore_scripts = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "https://weeecycle-production.up.railway.app/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]